import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import ToastProvider from "@/providers/ToastProvider";
import Navigation from "@/components/dashboard/Navigation";
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/AuthOptions';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
 
  return (
    <html lang="en">
      <body className= {inter.className}>
        <ToastProvider />
        <NextAuthSessionProvider>
          {session?.user?.email && <Navigation/>}
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
